version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: monthly
    commit-message:
      prefix: ":arrow_up: ci"
      include: "scope"

  # Maintain dependencies for Composer
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ":arrow_up: chore"
      include: "scope"
    labels:
      - dependencies
    open-pull-requests-limit: 0
