services:
  php:
    env_file: ../../config/environments/.env.local
    build:
      context: ../../
      dockerfile: deployment/docker/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.3}
        COMPOSER_VERSION: ${COMPOSER_VERSION:-lts}
    working_dir: /app
    volumes:
      - ../../:/app
