services:
  composer:
    env_file: ../../config/environments/.env.local
    build:
      context: ../../
      dockerfile: deployment/docker/composer/Dockerfile
      args:
        COMPOSER_VERSION: ${COMPOSER_VERSION:-lts}
    volumes:
      - ../../:/app
    working_dir: /app
