name: Security

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  composer_audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 8.3 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Composer audit
        run: composer audit
